#!/usr/bin/env php
<?php
/**
 * Project init wizard
 *
 * @link http://taiga.systems
 * @copyright Copyright (c) 2018 Taiga Systems
 * @author Pavel Pavlenko region23@gmail.com
 */

print("*** Первичная инициализация проекта ***\n\n");

do {
    $projectName = readline("Введи название проекта на английском языке\n>>> ");
} while ($projectName === '');

do {
    $mysqlRootPassword = readline("Придумай root-пароль для подключения к MySQL\n>>> ");
} while ($mysqlRootPassword === '');

do {
    $mysqlPassword = readline("Придумай пароль для пользователя user для подключения к MySQL\n>>> ");
} while ($mysqlPassword === '');

do {
    $projectType = readline("Создать новый проект (1) или инициализировать существующий проект (2)?\n>>> ");
} while ($projectType !== '1' && $projectType !== '2');

do {
    $serverType = readline("Проект инициализируется для боевого сервера (prod) или компьютера разработчика (dev)?\n>>> ");
} while ($serverType !== 'dev' && $serverType !== 'prod');

$appExist = false;
if (file_exists("./app") && is_dir("./app")) {
    $appExist = true;
}

if ($projectType === "1" && !$appExist) {
    shell_exec('composer create-project --prefer-dist yiisoft/yii2-app-basic app');
} elseif ($projectType === "2") {
    readline("Создайте папку app/ и переместите в неё ваш Yii2-проект. После этого нажмите клавишу Enter.");
}

# Чистим от мусора папку с проектом
shell_exec("rm -rf app/vagrant app/.gitignore app/docker-compose.yml app/LICENSE.md app/README.md app/Vagrantfile");

# Вариант для Dev
if ($serverType === "dev") {
    shell_exec("cp -f templates/Caddyfile.dev docker/Caddyfile");
} elseif ($serverType === "prod") {
    # Вариант для Production
    shell_exec("cp -f templates/Caddyfile.prod docker/Caddyfile");

    do {
        $projectDomain = readline("Введи название домена, на котором будет располагаться проект (без http://)\n >>> ");
    } while ($projectDomain === '');

    do {
        $phpmyadminDomain = readline("Введи название домена, на котором будет располагаться PhpMyAdmin (без http://)\n >>> ");
    } while ($phpmyadminDomain === '');
}

# Операции одинаковые для обоих серверов
# Скопировать app/runtime/.gitignore в app/vendor/.gitignore
shell_exec("cp -f app/runtime/.gitignore app/vendor/.gitignore");
shell_exec("cp -f templates/docker-compose.yml docker-compose.yml");
shell_exec("cp -f templates/db.php app/config/db.php");
shell_exec("cp -f templates/update.sh update.sh");


$stringToReplace = [
    "{PROJECT_NAME}" => $projectName,
    "{MYSQL_ROOT_PASSWORD}" => $mysqlRootPassword,
    "{MYSQL_PASSWORD}" => $mysqlPassword,
    "{PHPMYADMIN_DOMAIN}" => $phpmyadminDomain,
    "{PROJECT_DOMAIN}" => $projectDomain
];

$replaceInFiles = [
    'docker-compose.yml',
    'app/config/db.php',
    'docker/Caddyfile',
    'update.sh'
];


foreach ($replaceInFiles as $filename) {
    //read the entire string
    $str = file_get_contents($filename);

    foreach ($stringToReplace as $oldVal => $newVal) {
        $str = str_replace($oldVal, $newVal, $str);
    }

    //write the entire string
    file_put_contents($filename, $str);
}


# Накатываем все зависимости composer
shell_exec("bash composer_install.sh");
