version: '3'
services:
  mysql_db:
    container_name: test_mysql_db
    build:
      context: ./docker
      dockerfile: Dockerfile_mysql
    volumes:
    - ./mysql:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    command: --character-set-server=utf8 --collation-server=utf8_general_ci


  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: test_mysql_db
    #restart: always
    depends_on:
    - mysql_db
    volumes:
    - /sessions

  php:
    container_name: test_php
    build:
      context: ./docker
      dockerfile: Dockerfile_php
    volumes:
    - ./app:/app
    #restart: always
    depends_on:
    - mysql_db

  caddy:
    container_name: test_caddy
    build:
      context: ./docker
      dockerfile: Dockerfile_caddy
    image: abiosoft/caddy
    depends_on:
    - mysql_db
    - phpmyadmin
    volumes:
    - ./docker/.caddy:/root/.caddy/
    - ./app:/app
    ports:
    - 80:80
    - 443:443
    - 2015:2015
    - 8000:8000
    - 8001:8001
