version: '3'
services:
  mysql_db:
    restart: always
    container_name: fsdf_mysql_db
    build:
      context: ./docker
      dockerfile: Dockerfile_mysql
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: w
      MYSQL_DATABASE: fsdf
      MYSQL_USER: user
      MYSQL_PASSWORD: f
    command: --character-set-server=utf8 --collation-server=utf8_general_ci


  phpmyadmin:
    restart: always
    container_name: fsdf_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: w
      PMA_HOST: fsdf_mysql_db
    depends_on:
    - mysql_db
    volumes:
    - /sessions

  php:
    restart: always
    container_name: fsdf_php
    build:
      context: ./docker
      dockerfile: Dockerfile_php
    volumes:
    - ./app:/app
    depends_on:
    - mysql_db

  caddy:
    restart: always
    container_name: fsdf_caddy
    build:
      context: ./docker
      dockerfile: Dockerfile_caddy
    image: abiosoft/caddy
    depends_on:
    - mysql_db
    - phpmyadmin
    volumes:
    - ./docker/.caddy:/root/.caddy/
    - ./app:/app
    ports:
    - 80:80
    - 443:443
    - 2015:2015
    
    
