version: '3'
services:
  mysql_db:
    #restart: always
    container_name: {PROJECT_NAME}_mysql_db
    build:
      context: ./docker
      dockerfile: Dockerfile_mysql
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: {MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: {PROJECT_NAME}
      MYSQL_USER: user
      MYSQL_PASSWORD: {MYSQL_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci


  phpmyadmin:
    #restart: always
    container_name: {PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: {MYSQL_ROOT_PASSWORD}
      PMA_HOST: {PROJECT_NAME}_mysql_db
    depends_on:
    - mysql_db
    volumes:
    - /sessions

  php:
    #restart: always
    container_name: {PROJECT_NAME}_php
    build:
      context: ./docker
      dockerfile: Dockerfile_php
    volumes:
    - ./app:/app
    depends_on:
    - mysql_db

  caddy:
    #restart: always
    container_name: {PROJECT_NAME}_caddy
    build:
      context: ./docker
      dockerfile: Dockerfile_caddy
    image: abiosoft/caddy
    depends_on:
    - mysql_db
    - phpmyadmin
    volumes:
    - ./docker/.caddy:/root/.caddy/
    - ./app:/app
    ports:
    - {PROJECT_PORT}:{PROJECT_PORT}
    - {PHPMYADMIN_PORT}:{PHPMYADMIN_PORT}
    #- 2015:2015
